const MasterCard =
  "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Mastercard-logo.svg/773px-Mastercard-logo.svg.png";

const VisaCard =
  "https://raw.githubusercontent.com/aaronfagan/svg-credit-card-payment-icons/master/flat-rounded/visa.svg?sanitize=true";

export default [
  {
    id: 1,
    area: 100,
    payable: 200,
    active: false,
    cardNumber: "5300160019008900",
    cardHolderName: "Muhammad Rizwan",
    cardType: "master",
    imgSrc: MasterCard,
    date: "07-June-2020",
    name: "Württemberg Forest 1",
    description: "Block X - 100 sq Patch - Germany",
    overdue: true,
    nextPaymentAmount: 200,
    subscription: "Yearly Subscription",
    nextDate: "07-06-2021",
    cardExpiryMonth: "03",
    cardExpiryYear: "2025",
    cardCVV: "276",
    paymentMethod: "Credit/Debit Card",
    history: [
      {
        area: 100,
        periodFrom: "07-06-2018",
        paid: 200,
        cardNumber: "5300160019008900",
        cardHolderName: "Muhammad Rizwan",
        cardExpiryMonth: "03",
        cardExpiryYear: "2025",
        cardCVV: "276",
        cardType: "master",
        imgSrc: MasterCard,
        date: "07-06-2019",
        name: "Württemberg Forest 1",
        description: "Block X - 100 sq Patch - Germany",
        paymentMethod: "Credit/Debit Card",
      },
      {
        area: 300,
        periodFrom: "07-06-2017",
        paid: 600,
        cardNumber: "5300160019008900",
        cardHolderName: "Muhammad Rizwan",
        cardExpiryMonth: "03",
        cardExpiryYear: "2025",
        cardCVV: "276",
        cardType: "master",
        imgSrc: MasterCard,
        date: "07-06-2018",
        name: "Württemberg Forest 1",
        description: "Block X - 100 sq Patch - Germany",
        paymentMethod: "Credit/Debit Card",
      },
      {
        area: 500,
        periodFrom: "07-06-2016",
        paid: 1000,
        cardNumber: "5300160019008900",
        cardHolderName: "Muhammad Rizwan",
        cardExpiryMonth: "03",
        cardExpiryYear: "2025",
        cardCVV: "276",
        cardType: "master",
        imgSrc: MasterCard,
        date: "07-06-2017",
        name: "Württemberg Forest 1",
        description: "Block X - 100 sq Patch - Germany",
        paymentMethod: "Credit/Debit Card",
      },
    ],
  },
  {
    id: 2,
    area: 5000,
    payable: 10000,
    active: false,
    cardNumber: "4242424242424242",
    cardHolderName: "Tobias Kreuzig",
    cardType: "visa",
    imgSrc: VisaCard,
    date: "01-08-2020",
    name: "Württemberg Forest 2",
    description: "Block X - 200 sq Patch - Germany",
    overdue: false,
    nextPaymentAmount: 10000,
    subscription: "Yearly Subscription",
    paymentMethod: "Credit/Debit Card",
    cardExpiryMonth: "09",
    cardExpiryYear: "2023",
    cardCVV: "276",
    nextDate: "01-08-2021",
    history: [
      {
        area: 5000,
        periodFrom: "01-08-2018",
        paid: 10000,
        cardNumber: "4242424242424242",
        cardHolderName: "Tobias Kreuzig",
        cardExpiryMonth: "09",
        cardExpiryYear: "2023",
        paymentMethod: "Credit/Debit Card",
        cardCVV: "276",
        cardType: "visa",
        imgSrc: VisaCard,
        date: "01-08-2019",
        name: "Württemberg Forest 1",
        description: "Block X - 100 sq Patch - Germany",
      },
      {
        area: 5000,
        periodFrom: "01-08-2017",
        paid: 10000,
        cardNumber: "4242424242424242",
        cardHolderName: "Tobias Kreuzig",
        cardType: "visa",
        paymentMethod: "Credit/Debit Card",
        imgSrc: VisaCard,
        date: "01-08-2018",
        cardExpiryMonth: "09",
        cardExpiryYear: "2023",
        cardCVV: "276",
        name: "Württemberg Forest 1",
        description: "Block X - 100 sq Patch - Germany",
      },
    ],
  },
];
